version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
    - ./project:/usr/src/app
    restart: on-failure
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - redis
    env_file:
      - ./project/.env
    command: python manage.py runserver 0.0.0.0:8000
  celery:
    build:
      context: .
    command: celery -A MAIN_APP worker --loglevel INFO
    volumes:
       - ./project:/usr/src/app
    depends_on:
      - redis
    env_file:
      - ./project/.env
  redis:
    image: redis